### ISSUE TITLE
Cannot Add Skill Points

### ISSUE THREAD

**Issue by DanteAyagawe** [stoneman2/LethalProgression#1]
When adding points, it doesn't work, also I noticed there's HP points, how to add hp?

**Comment by DanteAyagawe** [comment]
This only happens after gaining enough points, after that I am unable to add more points to an attribute, only in the beginning were I have 5 points

**Comment by stoneman2** [comment]
Should be fixed in the latest update. Are you on the latest version?

**Comment by stoneman2** [comment]
Fixed.

**Comment by DanteAyagawe** [comment]
Thankies
