### ISSUE TITLE
Stuck lug

### ISSUE THREAD

**Issue by AkimChan** [stoneman2/LethalProgression#10]
![изображение_2023-12-07_235006476](https://github.com/stoneman2/LethalProgression/assets/110656307/7e0b393f-cc6f-4a51-a238-efed58f88ef4)
When I start the lobby, everything just lags after the last update, esc also doesn’t work, ship ambient can be heard, chat also doesn’t work

**Comment by AkimChan** [comment]
ok, I spent 2 hours trying to figure out where the conflict is in the mods, and I found out that the Skinwalkers mod together with LethalProgression creates this error

**Comment by stoneman2** [comment]
Fixed
