### ISSUE TITLE
 Console Spam

### ISSUE THREAD

**Issue by Deadlesszombie** [stoneman2/LethalProgression#12]
Error loading the game:
![image](https://github.com/stoneman2/LethalProgression/assets/24554780/b4dba112-1b7c-425e-8c6a-ed3a3c7cc1f2)

Mid-game spam:
![image](https://github.com/stoneman2/LethalProgression/assets/24554780/e46a1e3f-b09d-42cf-8609-17bbfc8c4390)

Not a problem in orbit or at the company HQ, but on a map console gets spammed with these errors

Any ideas? Assuming an incompatibility somewhere

Mods list:
BepInExPack by BepInEx
MoreCompany by notnotnotswipez
More_Suits by x753
LateCompany by anormaltwig
ShipLoot by tinyhoot
Helmet_Cameras by RickArg
HookGenPatcher by Evaisa
LethalLib by Evaisa
AdditionalSuits by AlexCodesGames
LetMeLookDown by FlipMods
ItemQuickSwitch by vasanex
MoreItems by Drakorle
FOV_Adjust by Rozebud
LethalFashion by BatTeam
Strange_Objects by togglemybits
LCBetterSaves by Pooble
WeatherMultipliers by Blorb
SCP_Foundation_Suit by TeamClark
LC_API by 2018
LethalEscape by xCeezy
LethalProgression by Stoneman

**Comment by stoneman2** [comment]
Try again with 1.3.0

**Comment by stoneman2** [comment]
Fixed
