### ISSUE TITLE
Potential Cross compat issue with mikes tweaks?

### ISSUE THREAD

**Issue by Darkmega18** [stoneman2/LethalProgression#14]
I have this and mikes tweaks installed, when I've gone to pick up more items than the default it displays the extra hand slots I can use, but thinks my inventory is full.
It feels like the hands upgrade might be forcing it back to default so it can upgrade itself? Not sure otherwise.

Similarly if this is occurring there might even be issues with the late game upgrades mods and some of the other settings for sprint etc.

**Comment by Darkmega18** [comment]
I set them to default by leaving them at zero. but haven't had the chance to check if the upgrades can then go above it afterwards.

**Comment by stoneman2** [comment]
Fixed

**Comment by Darkmega18** [comment]
Naisu! I saw it not long after you uploaded it actually.
