### ISSUE TITLE
Cannot open the Skills Tab/Error in BepInEx

### ISSUE THREAD

**Issue by Florentb18** [stoneman2/LethalProgression#16]
So when i load the mod in alone, get in the game and try to press the "Skills" button. I get an error from Unity Log that looks like this[]

![error pt1](https://github.com/stoneman2/LethalProgression/assets/129381155/25573138-b2c5-4fcd-ae9b-41d50fbec832)

And for some reasons the Level required to "level up" is this instead of the original one.

![error pt2](https://github.com/stoneman2/LethalProgression/assets/129381155/5b93dd14-4420-4a0d-978c-2fd11e2da1f2)

My friend installed the mod as well and compared to me, it works perfectly, any idea what the cause of the problem is?

**Comment by stoneman2** [comment]
Try again with 1.3.0

**Comment by Florentb18** [comment]
Tried again, got some new errors this time.

![error pt4](https://github.com/stoneman2/LethalProgression/assets/129381155/148ca632-7d3a-4b69-8503-3d2353cdde23)

It shows 0/0 instead now.

**Comment by damien2502** [comment]
Same problem here

**Comment by stoneman2** [comment]
Anyone here able to contact me on Discord? I am unable to reproduce this at all. It has been happening for the past week and I don't understand why. Need extensive debugging.
@stoneman on discord.

**Comment by Florentb18** [comment]
Sure thing, expect an invite from my username Florentb18

**Comment by stoneman2** [comment]
Fixed
