### ISSUE TITLE
[Suggestion] Add Config to Disable Decrease Skill Point That Already Upgraded

### ISSUE THREAD

**Issue by vgomasjaya** [stoneman2/LethalProgression#17]
Can you add more config to disable decrease skill point that already upgraded?

Thank you

**Comment by stoneman2** [comment]
what does this mean

**Comment by vgomasjaya** [comment]
I mean config option that make we can't decrease the skill point that we've already upgraded (hide -1, -2, -5 in skill upgrade)

**Comment by Darkmega18** [comment]
> what does this mean

I believe they mean, "no respeccing" mode. Where your point choices are final.

**Comment by stoneman2** [comment]
Fixed
