### ISSUE TITLE
value of Team Loot skill bug?

### ISSUE THREAD

**Issue by vbnshi** [stoneman2/LethalProgression#19]
1.2.2 versions 
For example, a player gets 5% of loot value when he clicks skills,However, when another player clicks a skill, 3% times 3% happens instead of 3% plus 3%

**Comment by vbnshi** [comment]
Maybe this skill is too strong, I think it can be replaced with a map with more loot

**Comment by vbnshi** [comment]
After all four players have clicked skills, one loot is worth 500

**Comment by Darkmega18** [comment]
anything is too strong if you minmax it.

**Comment by stoneman2** [comment]
I'll check it out thanks

**Comment by stoneman2** [comment]
I just read it again, 1.2.2?? I just fixed it in 1.3.0
