### ISSUE TITLE
hand slots upgrade option disappear

### ISSUE THREAD

**Issue by TShineCN** [stoneman2/LethalProgression#24]
The mod you made is amazing. My friends and I really enjoy playing with it. But I found a small issue, which is that when using both your mod and these three mods(ReservedItemSlotCore\ReservedFlashlightSlot\ReservedWalkieSlot )  at the same time, the hand slots upgrade option will disappear. May I ask if this is intentionally set by the mod or if there is an issue?
![1](https://github.com/stoneman2/LethalProgression/assets/54096173/e3dfdabf-bece-443c-a7cc-e231122e9e6e)
![2](https://github.com/stoneman2/LethalProgression/assets/54096173/07b07de1-3c10-497b-8b07-e3d9caaba32f)

**Comment by stoneman2** [comment]
Intended. It's incompatible.

**Comment by TShineCN** [comment]
> 有意的。这是不相容的。
Thank you for your reply. I understand now

**Comment by TShineCN** [comment]
> Intended. It's incompatible.

Thank you for your reply. I understand now
