### ISSUE TITLE
save file bug

### ISSUE THREAD

**Issue by vbnshi** [stoneman2/LethalProgression#25]
Only bepinx-Bepinexpack-5.4.2100 and Stoneman-LethalProgression-1.3.1 are available
LocalLow\ZeekerssRBLX\Lethal Company\lethalprogression\save3.txt
No experience saved. It's all 0

**Comment by vbnshi** [comment]
Either a normal exit from the game or a forced exit from the game

**Comment by stoneman2** [comment]
Game saves only happen when you quit in orbit

**Comment by vbnshi** [comment]
> Game saves only happen when you quit in orbit

Came back from the test，again all 0

**Comment by sjalsburen** [comment]
yea im having the same issue o it not saving and the inventory slots dont work either

**Comment by NiHuShu** [comment]
I can also confirm that the values are not saved

**Comment by stoneman2** [comment]
Will fix

**Comment by stoneman2** [comment]
Fixed
