### ISSUE TITLE
Unable to join multiplayer saves with LateGameUpgrades

### ISSUE THREAD

**Issue by GoliathX211** [stoneman2/LethalProgression#31]
We are getting the "An Error Occured" message when joining each other.
We tested first with only Lethal Progression since we wanted that one on the top of priority and we were able to make a new save and rejoin it with multiplayer. As soon as we added LGU, we had this issue.
We were having this issue with a larger modpack but we seemed to isolate it down to your mod and LGU.

Here's an issue on their tracker:
https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/40

**Comment by Malcolm-Q** [comment]
Are you installing mods via a mod manager or manually?
You're sure you installed this mod and it's dependencies correctly? I can try test it soon but I'm pretty sure these two mods work fine together.

**Comment by Malcolm-Q** [comment]
By "this mod" I meant LGU. I thought I commented this on my repo lol.

It needs hookgen patcher and lethal lib.

**Comment by stoneman2** [comment]
I can't possibly account for every mod under the sun

**Comment by Malcolm-Q** [comment]
I've seen quite a few people use ours together, I think you can close this.
