### ISSUE TITLE
Is xp supposed to reset?

### ISSUE THREAD

**Issue by ImpulsiveLad** [stoneman2/LethalProgression#38]
Everytime I made a new world I am keeping my levels, can it not do that? I kinda want to earn them as the quotas go on

**Comment by ImpulsiveLad** [comment]
like I'm logging in and I have like 47 levels can I have 0?

**Comment by ImpulsiveLad** [comment]
If this is intentional then imo you should be able to config
1. whether xp is kept across saves and new ones
2. whether xp is reset after being jettisoned by failure

**Comment by stoneman2** [comment]
I made github templates for people to follow and people don't follow them
I'd love to know some details but you didn't seem to read it

**Comment by ImpulsiveLad** [comment]
It caused by an incompatibility with bettersaves
