### ISSUE TITLE
Hand Slot upgrade not appearing in skill list.

### ISSUE THREAD

**Issue by Pojo267** [stoneman2/LethalProgression#39]
Version:
v1.3.2

I would assume some conflict is causing the issue, but I do not see the Hand Slots upgrade in the skills menu at all. Config definitely has it set to be enabled.

Mod List:
BepInExPack
MoreCompany
ShipLoot
AdditionalSuits
FlashlightToggle
HotbarPlus
WalkieUse
More_Emotes
ReservedItemSlots
ReservedWalkieSlot
MoreItems
ShipLobby
TerminalApi
Terminal_Clock
LetMeLookDown
Skinwalkers
AlwaysHearActiveWalkies
Boombox_Controller
HookGenPatcher
LethalLib
LethalThings
LethalFashion
IntroTweaks
EladsHUD
Helmet_Cameras
LethalProgression

**Comment by Pojo267** [comment]
After some testing, the hand slot appears to vanish when the ReservedWalkieSlot mod is enabled.

**Comment by ANYX-The-Artist** [comment]
Yes, that's intentional and not a bug.

**Comment by Pojo267** [comment]
> Yes, that's intentional and not a bug.

May I ask why?

**Comment by stoneman2** [comment]
Game breaks otherwise
